# Generated by Django 3.0.3 on 2020-04-21 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('msg_text', models.CharField(max_length=100)),
                ('msg_timestamp', models.DateTimeField(auto_now_add=True)),
                ('msg_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='group.Group')),
            ],
            options={
                'ordering': ('msg_timestamp',),
            },
        ),
    ]
