# Generated by Django 3.0.3 on 2020-04-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_remove_group_group_users'),
        ('user', '0002_auto_20200415_1601'),
        ('message', '0002_message_msg_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='user.User'),
        ),
    ]
