# Generated by Django 3.0.3 on 2020-04-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200415_1601'),
        ('group', '0002_group_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_in_group', to='user.User'),
        ),
    ]
