# Generated by Django 3.0.3 on 2020-04-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20200417_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_users',
        ),
    ]
