# Generated by Django 3.0.3 on 2020-04-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_group', models.ManyToManyField(null=True, to='group.Group')),
                ('user_recent_message', models.ManyToManyField(null=True, to='message.Message')),
            ],
        ),
    ]
