# Generated by Django 3.0.3 on 2020-04-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_group_users'),
        ('message', '0002_message_msg_sender'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.ManyToManyField(blank=True, null=True, to='group.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_recent_message',
            field=models.ManyToManyField(blank=True, null=True, to='message.Message'),
        ),
    ]
